export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as NewTicket} from "./NewTicket"
export {default as Tickets} from "./Tickets"
export {default as Ticket} from "./Ticket"